import { Injectable, signal } from '@angular/core';
import { Gig } from '../models/gig.model';

@Injectable({ providedIn: 'root' })
export class GigService {
  private readonly _gigs: Gig[] = [
    {
      id: 1,
      title: 'Coffee Counter Helper',
      employer: 'Brewed Bliss Cafe',
      category: 'cafe',
      emoji: '☕',
      duration: '2 hours',
      pay: '₹120/hr',
      payType: 'hourly',
      location: 'Pune',
      area: 'Koregaon Park',
      slots: 1,
      date: 'Today',
      time: '4:00 PM – 6:00 PM',
      description: 'Humari busy evening shift ke liye ek energetic helper chahiye! Kaam hai coffee orders lena, table clean karna aur customers ko smile ke saath greet karna. No experience needed – just vibes! 🎵',
      tags: ['No Experience', 'Evening Shift', 'Fun Workplace'],
      color: '#FF9F43',
      accentColor: '#FFF3E0',
      bgPattern: 'cafe',
      isUrgent: true,
      postedAgo: '30 min ago',
    },
    {
      id: 2,
      title: 'Book Stall Assistant',
      employer: 'PageTurner Books',
      category: 'books',
      emoji: '📚',
      duration: '3 hours',
      pay: '₹100/hr',
      payType: 'hourly',
      location: 'Pune',
      area: 'FC Road',
      slots: 2,
      date: 'Tomorrow',
      time: '10:00 AM – 1:00 PM',
      description: 'Ek book lover girl ya boy chahiye jo humari stall pe customers ki help kare. Books arrange karo, suggestions do, aur billing mein help karo. Book readers ko extra preference! 📖✨',
      tags: ['Book Lovers', 'Morning Shift', '2 Positions'],
      color: '#4D96FF',
      accentColor: '#E8F1FF',
      bgPattern: 'books',
      isUrgent: false,
      postedAgo: '2 hrs ago',
    },
    {
      id: 3,
      title: 'Event Coordinator Helper',
      employer: 'Spark Events Co.',
      category: 'events',
      emoji: '🎉',
      duration: '5 hours',
      pay: '₹800',
      payType: 'fixed',
      location: 'Pune',
      area: 'Viman Nagar',
      slots: 3,
      date: 'Sat, 14 Jun',
      time: '2:00 PM – 7:00 PM',
      description: 'College farewell party organize karne mein help chahiye! Decoration setup, guest management, photography assist. Super fun environment, free food bhi milega! 🎊🍕',
      tags: ['Free Food!', 'Fixed Pay', '3 Positions'],
      color: '#C77DFF',
      accentColor: '#F5E8FF',
      bgPattern: 'events',
      isUrgent: false,
      postedAgo: '1 day ago',
    },
    {
      id: 4,
      title: 'Retail Store Helper',
      employer: 'StyleZone Clothing',
      category: 'retail',
      emoji: '🛍️',
      duration: '4 hours',
      pay: '₹110/hr',
      payType: 'hourly',
      location: 'Pune',
      area: 'MG Road',
      slots: 1,
      date: 'Today',
      time: '6:00 PM – 10:00 PM',
      description: 'Weekend evening shift pe humari fashion store mein ek energetic person chahiye. Stock arrangement, trial room management, aur billing counter. Stylish log preferred! 👗😎',
      tags: ['Fashion Store', 'Evening Shift', 'Urgent!'],
      color: '#FF78C4',
      accentColor: '#FFE8F5',
      bgPattern: 'retail',
      isUrgent: true,
      postedAgo: '45 min ago',
    },
    {
      id: 5,
      title: 'Math Tuition Assistant',
      employer: 'BrainBoost Tuitions',
      category: 'tuition',
      emoji: '📖',
      duration: '2 hours',
      pay: '₹150/hr',
      payType: 'hourly',
      location: 'Pune',
      area: 'Kothrud',
      slots: 1,
      date: 'Daily',
      time: '7:00 PM – 9:00 PM',
      description: 'Class 8-10 ke students ko Math aur Science padhane ke liye helper chahiye. Engineering/Science students ko preference. Maths strong honi chahiye. 🧮🚀',
      tags: ['Daily Work', 'Best Pay', 'Science Students'],
      color: '#6BCB77',
      accentColor: '#E8F8EB',
      bgPattern: 'tuition',
      isUrgent: false,
      postedAgo: '3 hrs ago',
    },
    {
      id: 6,
      title: 'Food Delivery Rider',
      employer: 'QuickBites Kitchen',
      category: 'delivery',
      emoji: '🚴',
      duration: '3 hours',
      pay: '₹60/delivery',
      payType: 'fixed',
      location: 'Pune',
      area: 'Baner',
      slots: 2,
      date: 'Flexible',
      time: '12:00 PM – 3:00 PM',
      description: 'Lunch rush ke time pe deliveries karo. Apni bike chahiye. Short distance deliveries only (2-3 km radius). Roz ka payment! 🛵💨',
      tags: ['Own Bike', 'Daily Cash', 'Flexible Hours'],
      color: '#FF6B6B',
      accentColor: '#FFE8E8',
      bgPattern: 'delivery',
      isUrgent: false,
      postedAgo: '5 hrs ago',
    },
    {
      id: 7,
      title: 'Social Media Content Creator',
      employer: 'TrendyBites Restaurant',
      category: 'other',
      emoji: '📸',
      duration: '2 hours',
      pay: '₹500',
      payType: 'fixed',
      location: 'Pune',
      area: 'Aundh',
      slots: 1,
      date: 'Sun, 15 Jun',
      time: '1:00 PM – 3:00 PM',
      description: 'Humare naye restaurant ke liye Instagram reels aur photos create karo. Creative person chahiye jo food photography aur short videos bana sake. Free lunch included! 🍜📱',
      tags: ['Creative Work', 'Free Lunch', 'Photography'],
      color: '#FFD93D',
      accentColor: '#FFFBE8',
      bgPattern: 'other',
      isUrgent: false,
      postedAgo: '6 hrs ago',
    },
  ];

  selectedGig = signal<Gig | null>(null);
  currentIndex = signal<number>(0);

  getGigs(): Gig[] {
    return [...this._gigs];
  }

  getGigById(id: number): Gig | undefined {
    return this._gigs.find(g => g.id === id);
  }

  selectGig(gig: Gig) {
    this.selectedGig.set(gig);
  }

  clearSelected() {
    this.selectedGig.set(null);
  }
}
